#!/bin/bash
# run_xlarge_r2_mf2_dispatch.sh — Phase 5 benchmark: ModelFinder MPI model-level
# dispatch on xlarge_mf.fa with 4 Gadi normalsr SPR nodes.
#
# Shape: 4 nodes × 1 MPI rank/node × 104 OMP threads/rank = 4 ranks, 416 cores total.
# Each rank evaluates ~1/4 of all DNA models (Phase 1 round-robin stripe).
# After all ranks finish, Phase 2 MPI_Allreduce merges scores → rank 0 selects
# best-fit model, Phase 2 broadcast propagates to all ranks.
# Phase 3 (--mpi-ranks-per-node 1 default): no thread budget change needed for
# 1 rank/node — each rank owns all 104 OMP threads as-is.
#
# Fixed tree: use the tree generated by the correctness pre-test (same fixed_xlarge_tree.nwk
# used in test_xlarge_mf2_correctness.sh). This ensures:
#   1. ModelFinder gets the same starting topology as the np=1 correctness reference.
#   2. The multi-rank fast-NNI tree search (which runs before MF without -te) is skipped,
#      eliminating topology divergence between np=1 and np=4 results.
#   3. Best-fit model should be SYM+G4 — directly verifiable against pre-test result.
#
# Dataset: xlarge_mf.fa (200 taxa × 100,000 sites, 98,858 distinct patterns,
#          ~99% site-pattern compression, seed 202)
#          sha256: 66eaf64b9b7e561f52dc515198c0b7db6d68cd37ada9498b254777f2dde94c44
#
# Expected outcome (first time MF will show real speedup on production dataset):
#   Models per rank:   242  (vs 968 redundant in baseline)
#   Wall-time speedup: ~4×  (Model eval is embarrassingly parallel)
#   RAM per rank:      ~3 GB (well within 503 GB/node; no memory pressure)
#   Best-fit model:    must match np=1 correctness pre-test (xlarge_ref_np1.log)
#
# Prerequisites:
#   1. correctness pre-test passed: gadi-ci/test_xlarge_mf2_correctness.sh
#   2. binary built: build-mpi-mf2/iqtree3-mpi (Phase 1+2+3 edits applied)
#
# Related Gadi normalsr baselines for comparison:
#   PBS 167865976: 1 node × 104 OMP, v3.1.1 → 523.7 s (full IQ-TREE, MF + tree)
#   PBS 167932917: 1 node × 104 OMP, v3.1.2 canonical → ~523 s
#   PBS 167932918: 2 nodes × 2×104 OMP → 342 s (MPI tree search, still 968 MF models)
#
# For the ModelFinder wall-time baseline (np=1, 968 models), see:
#   xlarge_ref_np1.log from test_xlarge_mf2_correctness.sh
#
# Usage:
#   # Run correctness pre-test first:
#   qsub gadi-ci/test_xlarge_mf2_correctness.sh
#   # Then submit this:
#   qsub gadi-ci/run_xlarge_r2_mf2_dispatch.sh

#PBS -N iq-mf2-xlarge-dispatch
#PBS -P um09
#PBS -q normalsr
#PBS -l ncpus=416
#PBS -l mem=2000gb
#PBS -l walltime=06:00:00
#PBS -l wd
#PBS -l storage=scratch/um09
#PBS -j oe

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
PROJECT="${PROJECT:-um09}"
USER_ID="${USER:-$(whoami)}"
REPO_DIR="${REPO_DIR:-${HOME}/setonix-iq}"

MF2_DIR="${MF2_DIR:-/scratch/${PROJECT}/${USER_ID}/iqtree3-mf2}"
BUILD_DIR="${BUILD_DIR:-${MF2_DIR}/build-mpi-mf2}"
IQTREE="${IQTREE:-${BUILD_DIR}/iqtree3-mpi}"

BENCHMARKS="${MF2_DIR}/benchmarks"
DATASET_NAME="${DATASET:-xlarge_mf}"
DATA_PATH="${BENCHMARKS}/${DATASET_NAME}.fa"
SHA256_EXPECTED="66eaf64b9b7e561f52dc515198c0b7db6d68cd37ada9498b254777f2dde94c44"

# 4 nodes × 1 rank × 104 OMP = 416 cores.
NRANKS="${NRANKS:-4}"
OMP_PER_RANK="${OMP_PER_RANK:-104}"
TOTAL_THREADS=$(( NRANKS * OMP_PER_RANK ))
SEED="${SEED:-42}"

# Fixed tree from correctness pre-test — same topology used for np=1 and np=4 reference.
# Ensures ModelFinder starts from the same tree on every run (no MPI tree search divergence).
FIXED_TREE="${FIXED_TREE:-${MF2_DIR}/test_xlarge_mf2/fixed_xlarge_tree.nwk}"

LABEL="${LABEL:-${DATASET_NAME}_${TOTAL_THREADS}t_mf2dispatch_mpi${NRANKS}x${OMP_PER_RANK}_4node_fullnode}"

RUNS_DIR="${REPO_DIR}/logs/runs"
RESULTS_DIR="${MF2_DIR}/results_xlarge_mf2"
PREFIX="${RESULTS_DIR}/mf2_xlarge_${NRANKS}r"

KMP_BLOCKTIME="${KMP_BLOCKTIME:-200}"

# ── Module load ───────────────────────────────────────────────────────────────
if command -v module >/dev/null 2>&1; then
    module load openmpi/4.1.7         2>/dev/null || true
    module load intel-compiler-llvm   2>/dev/null || true
fi

# ── Preflight checks ──────────────────────────────────────────────────────────
if ! command -v mpirun >/dev/null 2>&1; then
    echo "ERROR: mpirun not found after module load openmpi/4.1.7." >&2; exit 4
fi
if [[ ! -x "${IQTREE}" ]]; then
    echo "ERROR: ${IQTREE} not found." >&2
    echo "       Build: cd ${BUILD_DIR} && /bin/gmake -j16 iqtree3" >&2; exit 5
fi
if ! ldd "${IQTREE}" 2>/dev/null | grep -qE 'libmpi(\.|_)'; then
    echo "ERROR: ${IQTREE} does not link libmpi — wrong build?" >&2; exit 6
fi
if ! strings "${IQTREE}" | grep -q "MF-MPI:"; then
    echo "WARNING: 'MF-MPI:' strings not found in binary — Phase 1+2 edits may not be compiled!" >&2
fi
if [[ ! -f "${FIXED_TREE}" ]]; then
    echo "ERROR: fixed tree not found: ${FIXED_TREE}" >&2
    echo "       Run gadi-ci/test_xlarge_mf2_correctness.sh first to generate it." >&2
    exit 7
fi
echo "[preflight] Fixed tree: ${FIXED_TREE}"
if [[ ! -s "${DATA_PATH}" ]]; then
    echo "ERROR: dataset ${DATA_PATH} not found or empty." >&2; exit 2
fi

# sha256 gate — same canonical file as all prior xlarge baselines
echo "[preflight] Verifying ${DATA_PATH} sha256..."
SHA256_LOCKFILE="${SHA256_LOCKFILE:-${REPO_DIR}/benchmarks/sha256sums.txt}"
if [[ -s "${SHA256_LOCKFILE}" ]]; then
    DATA_BASENAME="$(basename "${DATA_PATH}")"
    expected="$(awk -v f="${DATA_BASENAME}" '/^[[:space:]]*#/ {next} $2==f {print $1}' "${SHA256_LOCKFILE}")"
    if [[ -n "${expected}" ]]; then
        actual="$(sha256sum "${DATA_PATH}" | awk '{print $1}')"
        if [[ "${actual}" != "${expected}" ]]; then
            echo "ERROR: sha256 mismatch for ${DATA_BASENAME}" >&2; exit 3
        fi
        echo "[preflight] ${DATA_BASENAME} sha256 OK"
    fi
fi

# ── PBS node discovery ───────────────────────────────────────────────────────
if [[ ! -s "${PBS_NODEFILE:-/dev/null}" ]]; then
    echo "ERROR: PBS_NODEFILE missing — must run inside a PBS job." >&2; exit 8
fi
mapfile -t HOSTS < <(sort -u "${PBS_NODEFILE}")
if [[ "${#HOSTS[@]}" -ne "${NRANKS}" ]]; then
    echo "ERROR: expected ${NRANKS} nodes, got ${#HOSTS[@]} (${HOSTS[*]:-empty})" >&2
    echo "       Check #PBS -l ncpus=${TOTAL_THREADS} on normalsr (${NRANKS} full SPR nodes)." >&2
    exit 9
fi

# Topology check: ensure each node has 104 physical cores
LSCPU_SOCKETS="$(lscpu | awk -F: '/Socket\(s\)/{gsub(/^ +| +$/,"",$2); print $2; exit}')"
LSCPU_COREPS="$(lscpu  | awk -F: '/Core\(s\) per socket/{gsub(/^ +| +$/,"",$2); print $2; exit}')"
PHYSICAL_CORES="$(( ${LSCPU_SOCKETS:-2} * ${LSCPU_COREPS:-52} ))"
if [[ "${PHYSICAL_CORES}" -ne "${OMP_PER_RANK}" ]]; then
    echo "ERROR: head-node has ${PHYSICAL_CORES} physical cores, expected ${OMP_PER_RANK} (2×52 SPR)." >&2
    exit 10
fi

PBS_ID_SHORT="${PBS_JOBID:-local_$(date +%Y%m%d_%H%M%S)}"
PBS_ID_SHORT="${PBS_ID_SHORT%%.*}"
RUN_ID="gadi_${LABEL}_${PBS_ID_SHORT}"

mkdir -p "${RESULTS_DIR}" "${RUNS_DIR}"

# ── Hostfile for mpirun ───────────────────────────────────────────────────────
HOSTFILE="${RESULTS_DIR}/hostfile_${PBS_ID_SHORT}.txt"
awk '{c[$1]++} END {for (h in c) print h, "slots=" c[h]}' "${PBS_NODEFILE}" > "${HOSTFILE}"

# ── Rankfile: each of the 4 ranks owns all 104 cores on its node ──────────────
RANKFILE="${RESULTS_DIR}/rankfile_${PBS_ID_SHORT}.txt"
{
    for i in $(seq 0 $(( NRANKS - 1 ))); do
        echo "rank ${i}=${HOSTS[$i]} slot=0-$(( OMP_PER_RANK - 1 ))"
    done
} > "${RANKFILE}"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  IQ-TREE MF2 — ModelFinder model-level dispatch benchmark"
echo "║  run_id:        ${RUN_ID}"
echo "║  dataset:       ${DATA_PATH}"
echo "║  ranks × OMP:   ${NRANKS} × ${OMP_PER_RANK}  (= ${TOTAL_THREADS} total, ${NRANKS} nodes)"
for i in $(seq 0 $(( NRANKS - 1 ))); do
    echo "║  node ${i}:   ${HOSTS[$i]}  (rank ${i}, ${OMP_PER_RANK} OMP threads)"
done
echo "║  binary:        ${IQTREE}"
echo "║  fixed tree:    ${FIXED_TREE}"
echo "║  prefix:        ${PREFIX}"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "[benchmark] hostfile:"
cat "${HOSTFILE}" | sed 's/^/    /'
echo "[benchmark] rankfile:"
cat "${RANKFILE}" | sed 's/^/    /'

# ── Environment metadata capture ─────────────────────────────────────────────
ENV_JSON="${RESULTS_DIR}/env_${PBS_ID_SHORT}.json"
python3 - <<PYENV > "${ENV_JSON}"
import json, os, subprocess, hashlib

def sh(c, d=""):
    try: return subprocess.check_output(c, shell=True, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception: return d

def sha256(p):
    try:
        h = hashlib.sha256()
        with open(p, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""): h.update(chunk)
        return h.hexdigest()
    except Exception: return None

ds = "${DATA_PATH}"
hosts = "${HOSTS[*]}"
env = {
  "run_id": "${RUN_ID}", "label": "${LABEL}",
  "phase": "mf2_dispatch_phase5",
  "threads": ${TOTAL_THREADS},
  "mpi_ranks": ${NRANKS}, "omp_per_rank": ${OMP_PER_RANK},
  "mpi_ranks_per_node": 1,
  "placement": "mpi_${NRANKS}node_fullnode",
  "nodes": ${NRANKS},
  "hosts": hosts.split(),
  "hostname": sh("hostname"), "kernel": sh("uname -r"),
  "cpu": sh("lscpu | grep 'Model name' | head -1 | cut -d: -f2- | xargs"),
  "cpu_sockets": int(sh("lscpu | awk -F: '/Socket\\(s\\)/{print \$2}' | xargs", "0") or 0),
  "cpu_cores_per_socket": int(sh("lscpu | awk -F: '/Core\\(s\\) per socket/{print \$2}' | xargs", "0") or 0),
  "mem_total_kb": int(sh("awk '/MemTotal/{print \$2}' /proc/meminfo", "0") or 0),
  "mpi_version": sh("mpirun --version 2>&1 | head -1"),
  "iqtree_binary": "${IQTREE}",
  "iqtree_version": sh("${IQTREE} --version 2>&1 | head -1"),
  "date": sh("date -Iseconds"),
  "dataset": {
    "path": ds, "file": os.path.basename(ds),
    "size_bytes": os.path.getsize(ds) if os.path.isfile(ds) else None,
    "sha256": sha256(ds),
  },
  "pbs": {
    "job_id":   os.environ.get("PBS_JOBID"),
    "queue":    os.environ.get("PBS_QUEUE"),
    "ncpus":    os.environ.get("PBS_NCPUS") or os.environ.get("NCPUS"),
  },
}
print(json.dumps(env, indent=2))
PYENV
echo "[env] metadata written to ${ENV_JSON}"

# ── Benchmark run ─────────────────────────────────────────────────────────────
echo ""
echo "[benchmark] Starting ModelFinder MPI dispatch (${NRANKS} ranks, ${OMP_PER_RANK} OMP/rank)..."
echo "[benchmark] $(date '+%Y-%m-%d %H:%M:%S')"
echo ""

T_START=$(date +%s)

mpirun -np "${NRANKS}" \
    --map-by node:PE="${OMP_PER_RANK}" \
    --mca pml ucx \
    -x UCX_TLS=rc_mlx5,ud_mlx5,sm,self \
    -x UCX_NET_DEVICES=mlx5_0:1 \
    -x "OMP_NUM_THREADS=${OMP_PER_RANK}" \
    -x "OMP_PROC_BIND=close" \
    -x "OMP_PLACES=cores" \
    -x "OMP_DYNAMIC=false" \
    -x "KMP_BLOCKTIME=${KMP_BLOCKTIME}" \
    numactl --localalloc -- \
    "${IQTREE}" \
        -s "${DATA_PATH}" \
        -te "${FIXED_TREE}" \
        -m MF \
        -T "${OMP_PER_RANK}" \
        --seed "${SEED}" \
        --prefix "${PREFIX}" \
        --redo \
    2>&1

EXIT_CODE=$?
T_END=$(date +%s)
WALL_SECONDS=$(( T_END - T_START ))

echo ""
echo "[benchmark] $(date '+%Y-%m-%d %H:%M:%S')  exit=${EXIT_CODE}  wall=${WALL_SECONDS}s"

# ── Results summary ───────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════════"
echo " Phase 5 benchmark results"
echo "════════════════════════════════════════════════════════════════"

if [[ ${EXIT_CODE} -eq 0 && -f "${PREFIX}.log" ]]; then
    BEST_MODEL=$(grep "Best-fit model:" "${PREFIX}.log" | head -1)
    MF_TIME=$(grep -E "ModelFinder|Model selection" "${PREFIX}.log" | head -5 || true)
    TOTAL_TIME=$(grep "Total wall clock time" "${PREFIX}.log" | head -1 || true)

    echo "  dataset:     ${DATA_PATH}"
    echo "  ranks:       ${NRANKS}"
    echo "  OMP/rank:    ${OMP_PER_RANK}"
    echo "  wall time:   ${WALL_SECONDS}s"
    echo "  ${BEST_MODEL}"
    echo "  ${TOTAL_TIME}"
    echo ""
    echo "[Phase 1+2+3 diagnostics]"
    grep "MF-MPI:" "${PREFIX}.log" 2>/dev/null || echo "(none)"

    # Write run summary JSON for the dashboard
    RUN_JSON="${RUNS_DIR}/${RUN_ID}.json"
    python3 - <<PYRUN > "${RUN_JSON}"
import json, os, subprocess, re

def sh(c, d=""):
    try: return subprocess.check_output(c, shell=True, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception: return d

log = open("${PREFIX}.log").read() if os.path.isfile("${PREFIX}.log") else ""

best_model = next((m.group(1) for m in [re.search(r"Best-fit model:\s+(\S+)", log)] if m), None)
total_wall = next((float(m.group(1)) for m in [re.search(r"Total wall clock time used:\s+([\d.]+)", log)] if m), None)
mf_lines = [l.strip() for l in log.splitlines() if "MF-MPI:" in l]

result = {
  "run_id": "${RUN_ID}",
  "label":  "${LABEL}",
  "phase":  "mf2_dispatch_phase5",
  "dataset": "${DATASET_NAME}",
  "mpi_ranks": ${NRANKS},
  "omp_per_rank": ${OMP_PER_RANK},
  "total_threads": ${TOTAL_THREADS},
  "nodes": ${NRANKS},
  "wall_time_s": ${WALL_SECONDS},
  "iqtree_wall_time_s": total_wall,
  "best_fit_model": best_model,
  "mf_mpi_lines": mf_lines,
  "exit_code": ${EXIT_CODE},
  "pbs_job_id": os.environ.get("PBS_JOBID"),
  "date": sh("date -Iseconds"),
  "env_json": "${ENV_JSON}",
  "log": "${PREFIX}.log",
}
print(json.dumps(result, indent=2))
PYRUN
    echo "[results] run summary written to ${RUN_JSON}"
else
    echo "✗ IQ-TREE exited with ${EXIT_CODE} or log not found at ${PREFIX}.log"
fi

echo "════════════════════════════════════════════════════════════════"
echo "[benchmark] Outputs: ${RESULTS_DIR}/"
echo "[benchmark] Compare best-fit model against: test_xlarge_mf2/xlarge_ref_np1.log"
exit ${EXIT_CODE}
