#!/bin/bash
# run_xlarge_mf_audit.sh — MF-only MF2 scaling run for the audit (Tier 3).
#
# Runs the MF2 binary (um09 build-mpi-mf2/iqtree3-mpi — AVX-512 + R2 patch +
# LPT MF_WAITING fix) with `mpirun -np 1 --map-by node:PE=THREADS`, so it uses
# the SAME binary as the 4-node dispatch (PBS 168000131) but at a single rank.
# Protocol: `-m MF -te fixed_xlarge_tree.nwk --seed 1`.
#
# This produces the "MF-only MF2 single-node" Amdahl curve so the dispatch ◆
# point (PBS 168000131, 416T/59s) has a same-binary, same-protocol baseline.
#
# Required env vars (set via `qsub -v`):
#   THREADS    — OMP thread count (1, 4, 8, 16, 32, 64, 104)
#
# Optional env vars (defaults shown):
#   SEED=1                                  — standard protocol seed
#   LABEL=xlarge_mf_<T>t_mf2_mfonly_np1_seed1  — auto-derived
#
# Walltime budget per thread count (use `qsub -l walltime=...` to override):
#   1T   → 04:00:00    (expected ~1-3h)
#   4T   → 01:30:00    (~20-40m)
#   8T   → 01:00:00    (~10-20m)
#   16T  → 00:30:00    (~6-12m)
#   32T  → 00:30:00    (~3-6m)
#   64T  → 00:30:00    (~2-4m)
#   104T → 00:30:00    (~1-2m)
#
#PBS -N iq-xlarge-mfonly
#PBS -P um09
#PBS -q normalsr
#PBS -l ncpus=104
#PBS -l mem=200GB
#PBS -l walltime=01:00:00
#PBS -l wd
#PBS -l storage=scratch/um09
#PBS -j oe

set -euo pipefail

PROJECT="${PROJECT:-um09}"
USER_ID="${USER:-$(whoami)}"
REPO_DIR="${REPO_DIR:-${HOME}/setonix-iq}"
MF2_DIR="${MF2_DIR:-/scratch/${PROJECT}/${USER_ID}/iqtree3-mf2}"
BUILD_DIR="${BUILD_DIR:-${MF2_DIR}/build-mpi-mf2}"
IQTREE="${IQTREE:-${BUILD_DIR}/iqtree3-mpi}"
BENCHMARKS="${BENCHMARKS:-${MF2_DIR}/benchmarks}"
RUNS_DIR="${REPO_DIR}/logs/runs"
PROFILES_DIR="${PROFILES_DIR:-${MF2_DIR}/gadi-ci/profiles}"

DATASET_NAME="${DATASET:-xlarge_mf}"
THREADS="${THREADS:?THREADS env var required (1, 4, 8, 16, 32, 64, or 104)}"
SEED="${SEED:-1}"
# Fixed tree: same file used by the 4-node dispatch (PBS 168000131).
# Generated by the correctness pre-test (test_xlarge_mf2_correctness.sh).
FIXED_TREE="${FIXED_TREE:-${MF2_DIR}/test_xlarge_mf2/fixed_xlarge_tree.nwk}"
LABEL="${LABEL:-${DATASET_NAME}_${THREADS}t_mf2_mfonly_np1_seed1}"

DATA_PATH="${BENCHMARKS}/${DATASET_NAME}.fa"
[[ -f "${DATA_PATH}" ]] || DATA_PATH="${BENCHMARKS}/${DATASET_NAME}"
DATA_BASENAME="$(basename "${DATA_PATH}")"

[[ -f "${DATA_PATH}" ]]   || { echo "ERROR: dataset ${DATA_PATH} not found." >&2; exit 2; }
[[ -f "${FIXED_TREE}" ]]  || { echo "ERROR: fixed tree ${FIXED_TREE} not found — run test_xlarge_mf2_correctness.sh first." >&2; exit 2; }
[[ -x "${IQTREE}" ]]      || { echo "ERROR: binary ${IQTREE} not found." >&2; exit 5; }

SHA256_LOCKFILE="${SHA256_LOCKFILE:-${REPO_DIR}/benchmarks/sha256sums.txt}"
if [[ -s "${SHA256_LOCKFILE}" ]]; then
    expected="$(awk -v f="${DATA_BASENAME}" '/^[[:space:]]*#/ {next} $2==f {print $1}' "${SHA256_LOCKFILE}")"
    if [[ -n "${expected}" ]]; then
        actual="$(sha256sum "${DATA_PATH}" | awk '{print $1}')"
        if [[ "${actual}" != "${expected}" ]]; then
            echo "ERROR: sha256 mismatch for ${DATA_BASENAME}" >&2; exit 3
        fi
        echo "[preflight] ${DATA_BASENAME} sha256 OK"
    fi
fi

if command -v module >/dev/null 2>&1; then
    module load openmpi/4.1.7        2>/dev/null || true
    module load intel-compiler-llvm  2>/dev/null || true
fi

# Preflight: MPI runtime required
command -v mpirun >/dev/null 2>&1 || { echo "ERROR: mpirun not found after module load openmpi/4.1.7." >&2; exit 4; }

# Preflight: binary must link libmpi (MF2 build) and contain LPT fix string
if ! readelf -d "${IQTREE}" 2>/dev/null | grep -q 'NEEDED.*libmpi'; then
    echo "ERROR: ${IQTREE} does not link libmpi — expected build-mpi-mf2 (um09)." >&2; exit 6
fi
if ! grep -qa 'cost-sorted LPT stripe' "${IQTREE}"; then
    echo "ERROR: ${IQTREE} missing LPT fix — rebuild from gadi-spr-r2-avx512 @ abd98764." >&2; exit 11
fi
echo "[preflight] LPT fix: CONFIRMED"

export OMP_NUM_THREADS="${THREADS}"
export OMP_DYNAMIC=false
export OMP_PROC_BIND=close
export OMP_PLACES=cores
export OMP_WAIT_POLICY=PASSIVE
export GOMP_SPINCOUNT=10000
export KMP_BLOCKTIME="${KMP_BLOCKTIME:-200}"
export TMPDIR="${MF2_DIR}/tmp"
mkdir -p "${TMPDIR}"

PBS_ID_SHORT="${PBS_JOBID:-local_$(date +%Y%m%d_%H%M%S)}"
PBS_ID_SHORT="${PBS_ID_SHORT%%.*}"
RUN_ID="gadi_${LABEL}"
WORK_DIR="${PROFILES_DIR}/${LABEL}_${PBS_ID_SHORT}"
mkdir -p "${WORK_DIR}" "${RUNS_DIR}"
cd "${WORK_DIR}"

echo "╔═════════════════════════════════════════════════════════════╗"
echo "║  MF-only MF2 audit — ${THREADS}T (np=1, same binary as dispatch)"
echo "║  run_id:  ${RUN_ID}"
echo "║  dataset: ${DATA_PATH}"
echo "║  tree:    ${FIXED_TREE}"
echo "║  seed:    ${SEED}"
echo "║  binary:  ${IQTREE}"
echo "╚═════════════════════════════════════════════════════════════╝"

START_EPOCH=$(date +%s)
IQRC=0
mpirun -np 1 \
    --map-by "node:PE=${THREADS}" \
    -x OMP_NUM_THREADS \
    -x OMP_PROC_BIND \
    -x OMP_PLACES \
    -x OMP_WAIT_POLICY \
    -x KMP_BLOCKTIME \
    -x GOMP_SPINCOUNT \
    numactl --localalloc -- \
    "${IQTREE}" \
        -s "${DATA_PATH}" \
        -m MF \
        -te "${FIXED_TREE}" \
        -T "${THREADS}" \
        -seed "${SEED}" \
        --prefix "${WORK_DIR}/iqtree_mfonly" \
    > "${WORK_DIR}/iqtree_mfonly.log" 2>&1 || IQRC=$?
END_EPOCH=$(date +%s)
WALL=$(( END_EPOCH - START_EPOCH ))
echo "[mf-audit] rc=${IQRC} wall=${WALL}s"

# Write the run record JSON in the same schema used by
# tools/scaling_10M_analysis.py::load_xlarge_gadi().
/usr/bin/python3.11 - <<PYEOF
import json, os, re, subprocess
work, runs = "${WORK_DIR}", "${RUNS_DIR}"
rid, label = "${RUN_ID}", "${LABEL}"
threads = ${THREADS}; wall = ${WALL}; iqrc = ${IQRC}
dpath, ibin = "${DATA_PATH}", "${IQTREE}"

def sh(c, d=""):
    try: return subprocess.check_output(c, shell=True, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception: return d

log = os.path.join(work, "iqtree_mfonly.log")
rep_ll = None; iqwall = None; mf_wall = None; best_model = None
if os.path.isfile(log):
    for line in open(log, errors="replace"):
        if m := re.search(r"BEST SCORE FOUND\s*:\s*(-?[\d.]+)", line): rep_ll = float(m.group(1))
        if m := re.search(r"Total wall-clock time used:\s+([\d.]+)", line): iqwall = float(m.group(1))
        if m := re.search(r"Wall-clock time for ModelFinder:\s+([\d.]+)", line): mf_wall = float(m.group(1))
        if m := re.search(r"Best-fit model:\s+(\S+)\s+chosen", line): best_model = m.group(1)

record = {
  "run_id": rid, "pbs_id": "${PBS_ID_SHORT}",
  "platform": "gadi", "run_type": "profile", "label": label,
  "description": f"MF-only MF2 audit — np=1, {threads}T, AVX-512+R2+LPT, -m MF -te fixed_xlarge_tree.nwk --seed 1",
  "timing": [{
    "command": f"mpirun -np 1 {ibin} -s xlarge_mf.fa -m MF -te fixed_xlarge_tree.nwk -T {threads} -seed 1",
    "time_s": iqwall if iqwall is not None else wall,
    "mf_wall_s": mf_wall,
    "best_model": best_model,
    "memory_kb": 0,
  }],
  "verify": ([{"file": "xlarge_mf.fa", "status": "pass", "expected": rep_ll, "reported": rep_ll, "diff": 0.0}] if rep_ll is not None else []),
  "env": {
    "hostname": sh("hostname"), "date": sh("date -Iseconds"),
    "cpu":      sh("lscpu | grep 'Model name' | head -1 | cut -d: -f2- | xargs"),
    "cores":    int(sh("nproc","0") or 0),
    "icx":      sh("icx --version 2>/dev/null | head -1"),
    "kernel":   sh("uname -r"),
    "iqtree_version_tag": "v3.1.2",
    "pbs": {
      "job_id":      os.environ.get("PBS_JOBID"),
      "project":     "${PROJECT}",
      "ncpus":       os.environ.get("PBS_NCPUS") or os.environ.get("NCPUS"),
    },
  },
  "summary": {
    "pass": 1 if iqrc == 0 else 0, "fail": 0 if iqrc == 0 else 1,
    "total_time": iqwall if iqwall is not None else wall,
    "all_pass":   iqrc == 0,
  },
  "profile": {
    "dataset":    "xlarge_mf",
    "threads":    threads,
    "mpi_ranks":  1,
    "omp_per_rank": threads,
    "placement":  "omp_pin_numa_ft",
    "protocol":   "mf_only_fixed_tree_seed1",
    "fixed_tree": "fixed_xlarge_tree.nwk",
    "seed":       1,
    "build_tag":  "mf2_mfonly_np1_seed1_avx512_r2_lpt",
  },
  "non_canonical":       True,
  "non_canonical_label": f"MF-only MF2 audit · np=1 · {threads}T · -m MF -te seed=1",
}
out_path = os.path.join(runs, rid + ".json")
json.dump(record, open(out_path,"w"), indent=2, default=str)
print(f"[mf-audit] wrote {out_path}")
PYEOF

echo "[mf-audit] done."
exit "${IQRC}"
